name: Upload Files to Telegram

on: [push]

jobs:
  upload-to-telegram:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Telegram File Uploader
      uses: xz-dev/TelegramFileUploader@v1.1.1
      with:
        to-who: 'username'
        message: 'Here are your files!'
        files: |
        /path/to/file1
        /path/to/file2
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
